// Copyright © 2000 Microsoft Corporation.  All rights reserved.
// In installing/viewing this source code, you agree to the terms of the
// Microsoft Research Source License (MSRSL) included in the root of this source tree
// and available from http://www.vworlds.org/license.asp.

// vwstuex.idl : IDL source 
//

// This file will be processed by the MIDL tool to
// produce the type library (vwstudio.tlb) and marshalling code.

///////////////////////////////////////////////////////////////////////////////////////////////
// This file contains the interface definitions for:-
//
// IStudioExemplar : Interface for the studio exemplar. Primarily consists of property changed
// handlers for properties created by this exemplar.
///////////////////////////////////////////////////////////////////////////////////////////////

import "oaidl.idl";
import "ocidl.idl";

import "vwobject.idl";

	[
		object,
		uuid(717B5AA6-7267-11d1-959F-00C04FD91F4D),
		dual,
		helpstring("StudioExemplar Interface"),
		pointer_default(unique)
	]
	interface IStudioExemplar : IVWDispatch
	{
		[helpstring("CameraFollowsObject property changed handler.")] 
		HRESULT OnCameraFollowsObjectChanged([in] long lHint, [in] VARIANT varHintData);
		[helpstring("SelectionLock property changed handler.")] 
		HRESULT OnSelectionLockChanged([in] long lHint, [in] VARIANT varHintData);
		[helpstring("Gravity property changed handler.")] 
		HRESULT OnGravityChanged([in] long lHint, [in] VARIANT varHintData);
		[helpstring("CollisionDetection property changed handler.")] 
		HRESULT OnCollisionDetectionChanged([in] long lHint, [in] VARIANT varHintData);
		[helpstring("EditingMode property changed handler.")] 
		HRESULT OnEditingModeChanged([in] long lHint, [in] VARIANT varHintData);
		[helpstring("Method to return the type of a property in string format.")]
		HRESULT GetTypeFromProperty([in] IThing *pThing, [in] BSTR bstrPropName, [out, retval] BSTR* bstrType);
		[helpstring("Method to return the Interface ID of a property in string format.")]
		HRESULT GetIIDFromType([in] BSTR bstrType, [out, retval] BSTR* bstrIID);
	};
