/* Copyright © 2000 Microsoft Corporation.  All rights reserved. */
/* In installing/viewing this source code, you agree to the terms of the */
/* Microsoft Research Source License (MSRSL) included in the root of this source tree */
/* and available from http://www.vworlds.org/license.asp. */

/*********************************************************
   The DllData.c file is generated by MIDL compiler 
   To completely reconstruct this file, delete it and rerun MIDL
   on all the IDL files in this DLL, specifying this file for the
   /dlldata command line option

  We use our own version in vwystem so that we only 
  generate proxy/stub information for the .idl's we specify
  If you want to add proxy/stub marshalling for a new .idl,
  you must add it to the two macros below.

*********************************************************/

#define PROXY_DELEGATION

#include <rpcproxy.h>

#ifdef __cplusplus
extern "C"   {
#endif

EXTERN_PROXY_FILE( vwuiobjs )

PROXYFILE_LIST_START
/* Start of list */
  REFERENCE_PROXY_FILE( vwuiobjs ),


/* End of list */
PROXYFILE_LIST_END


DLLDATA_ROUTINES( aProxyFileList, GET_DLL_CLSID )

#ifdef __cplusplus
}  /*extern "C" */
#endif

/* end of generated dlldata file */
