// Copyright © 2000 Microsoft Corporation.  All rights reserved.
// In installing/viewing this source code, you agree to the terms of the
// Microsoft Research Source License (MSRSL) included in the root of this source tree
// and available from http://www.vworlds.org/license.asp.

#include <olectl.h>

// vwsystem.idl : IDL source for vwsystem.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (vwsystem.tlb) and marshalling code.

	import "oaidl.idl";
	import "ocidl.idl";

	// core
	import "vwobject.idl";
	import "vwprop.idl";
	import "vwclient.idl";
	import "vwserver.idl";
	import "vwadmin.idl";
	import "vwodb.idl";
//	import "avprof.idl";
	
	// tools
	import "vwanim.idl";
//	import "vwstats.idl";
	import "vwhtml.idl";
	import "inetfile.idl";
	import "dirserv.idl";
	import "authntic.idl";

	// exemplars
	import "vwsysex.idl";

[
	uuid(06E3A0F4-958F-11D0-9543-00C04FD91F4D),
	version(1.0),
	helpstring("vwsystem 1.0 Type Library")
]
library VWSYSTEMLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

// from vwbuffer.idl
	[
		uuid(590D9881-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("MarshallBuffer Object")
	]
	coclass MarshallBuffer
	{
		[default] interface IMarshallBuffer;
	};

	[
		uuid(590D9883-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("UnMarshallBuffer Object")
	]
	coclass UnMarshallBuffer
	{
		[default] interface IUnMarshallBuffer;
	};

// from vwobject.idl
	[
		uuid(590D986F-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("PropertyCollection Object")
	]

	coclass PropertyCollection
	{
		[default] interface IPropertyCollection;
	};

	[
		uuid(590D9871-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("PropertySecurity Object")
	]

	coclass PropertySecurity
	{
		[default] interface IPropertySecurity;
	};

	[
		uuid(590D9873-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("PropertyList Object")
	]

	coclass PropertyList
	{
		[default] interface IPropertyList;
	};

	[
		uuid(590D9875-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("PropertyMap Object")
	]
	coclass PropertyMap
	{
		[default] interface IPropertyMap;
	};

	[
		uuid(590D9877-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("COMModule Object")
	]
	coclass COMModule
	{
		[default] interface ICOMModule;
	};

	[
		uuid(590D9879-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("ScriptModule Object")
	]
	coclass ScriptModule
	{
		[default] interface IScriptModule;
	};

	[
		uuid(590D987B-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("Method Object")
	]
	coclass Method
	{
		[default] interface IMethod;
	};

	[
		uuid(590D987D-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("Thing Object")
	]
	coclass Thing
	{
		[default] interface IThing;
	};

	[
		uuid(590D987F-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("World Object")
	]
	coclass World
	{
		[default] interface IWorld;
		[source] interface IVWObjectSite;
	};

// from vwcomm.idl
	[
		uuid(7736D441-DBD6-11CF-A516-00AA00B595DB),
		helpstring("VWComm Class")
	]
	coclass VWComm
	{
		[default] interface IVWComm;
	};

	[
		uuid(7736D443-DBD6-11CF-A516-00AA00B595DB),
		helpstring("VWCommConnection Class")
	]
	coclass VWCommConnection
	{
		[default] interface IVWCommConnection;
	};

	[
		uuid(7736D445-DBD6-11CF-A516-00AA00B595DB),
		helpstring("VWCommMessage Class")
	]
	coclass VWCommMessage
	{
		[default] interface IVWCommMessage;
	};

// FastComm
	[
		uuid(00F5F3D4-95A0-4e8e-88BA-C7DB1F836CCB),
		helpstring("FastComm Class")
	]
	coclass FastComm
	{
		[default] interface IVWComm;
	};

	[
		uuid(00F5F3D6-95A0-4e8e-88BA-C7DB1F836CCB),
		helpstring("FastCommConnection Class")
	]
	coclass FastCommConnection
	{
		[default] interface IVWCommConnection;
	};

	[
		uuid(00F5F3D8-95A0-4e8e-88BA-C7DB1F836CCB),
		helpstring("FastCommMessage Class")
	]
	coclass FastCommMessage
	{
		[default] interface IVWCommMessage;
	};

// from vwclient.idl
	[
		uuid(590D9823-A417-11CF-9BF0-0080C7A56A8A),
		helpstring("VWClient Object")
	]
	coclass VWClient
	{
		[default] interface IVWClient;
		[source] interface IVWClientSite;
	};

	[ uuid(D4898802-20EF-11D0-8A96-00A0C9082583),
	  helpstring("Event interface for VWClientOCX Control") ]
	dispinterface _VWClientOCX
	{
		properties:
			//  Event interface has no properties

		methods:
			[id(1)] void OnConnect(IDispatch* pWorld);
			[id(2)] void OnDisconnect(IDispatch* pWorld);
			[id(3)] void OnUserConnect(IDispatch* pthing);
			[id(4)] void OnUserDisconnect(IDispatch* pthing);
			[id(5)] void OnUserReconnect(IDispatch* pNewClient, IDispatch* pNewWorld, IDispatch* pNewThing);
			[id(6)] void OnTrace(BSTR bstr);
			[id(7)] void OnReport(BSTR bstr, long lVal);
			[id(8)] void OnUIEvent(IDispatch* pthing, BSTR bstrEventName, VARIANT varArg);
	};

	[
		uuid(D4898803-20EF-11D0-8A96-00A0C9082583),
		helpstring("VWClientOCX Class")
	]
	coclass VWClientOCX
	{
		[default] interface IVWClientOCX;
		[default, source] interface _VWClientOCX;
	};

// from vwserver.idl
	[
		uuid(F8584902-00F4-11D0-A516-00AA00B595DB),
		helpstring("VWServer Class")
	]
	coclass VWServer
	{
		[default] interface IVWServer;
		[default, source] interface DVWServerEvents;
	};

// from vwodb.idl
	[
		uuid(8D20B9CE-E963-11CF-A516-00AA00B595DB),
		helpstring("VWObjectRepository Class")
	]
	coclass VWObjectRepository
	{
		[default] interface IVWObjectRepository;
	};

// from vwadmin.idl
	[
		uuid(02043F43-02B3-11d2-80F5-00C04FAD7D6D),
		helpstring("VWAdmin Object")
	]
	coclass VWAdmin
	{
		[default] interface IVWAdmin;
	};

// from inetfile.idl
	[
		uuid(120113E0-E936-11CF-87BD-00AA00B4DF93),
		helpstring("InternetFileManager Class")
	]
	coclass InternetFileManager
	{
		[default] interface IInternetFileManager;
	};

// from dirserv.idl
	[
		uuid(40A94351-9AE4-11D0-8587-00A0C90F2911),
		helpstring("DServ Class")
	]
	coclass DServ
	{
		[default] interface IDServ;
	};
	
// from vwanim.idl
	[
		uuid(FF08F5A8-2E6B-11D0-89AB-00A0C9054129),
		helpstring("VWAnimator Class")
	]
	coclass VWAnimator
	{
		[default] interface IVWAnimator;
	};

	[
		uuid(FF08F5AA-2E6B-11D0-89AB-00A0C9054129),
		helpstring("VWAnimation Class")
	]
	coclass VWAnimation
	{
		[default] interface IVWAnimation;
	};

	[
		uuid(FF08F5AC-2E6B-11D0-89AB-00A0C9054129),
		helpstring("VWAnimationCallback Class")
	]
	coclass VWAnimationCallback
	{
		[default] interface IVWAnimationCallback;
	};

// from vwhtml.idl
	[
		uuid(7E3832CD-4F4E-11D0-89AB-00A0C9054129),
		helpstring("VWHtml Class")
	]
	coclass VWHtml
	{
		[default] interface IVWHtml;
	};

	[
		uuid(7E3832CF-4F4E-11D0-89AB-00A0C9054129),
		helpstring("VWHtmlHelper Class")
	]
	coclass VWHtmlHelper
	{
		[default] interface IVWHtmlHelper;
	};

#if 0
// from vwstats.idl
	[
		uuid(13B24367-3EEF-11D0-8587-00A0C90F2911),
		helpstring("VWStatCol Class")
	]
	coclass VWStatCol
	{
		[default] interface IVWStatCol;
	};
#endif

// from menuitem.idl
	[
		uuid(D4916C26-00C2-11D0-8A96-00A0C9082583),
		helpstring("MenuItem Class")
	]
	coclass MenuItem
	{
		[default] interface IMenuItem;
	};

// from ocxproxy.idl
	[
		uuid(09362219-2570-11D1-83BF-00C04FB6FA46),
		helpstring("OCXProxy Class")
	]
	coclass OCXProxy
	{
		[default] interface IOCXProxy;
	};

// from avprof.idl
	[
		uuid(D4E7472C-2953-11D1-AFB6-00C04FB915AA),
		helpstring("AvatarProfile Class")
	]
	coclass AvatarProfile
	{
		[default] interface IAvatarProfile;
	};

	[
		uuid(D4E7472E-2953-11D1-AFB6-00C04FB915AA),
		helpstring("AvatarProfileData Class")
	]
	coclass AvatarProfileData
	{
		[default] interface IAvatarProfileData;
	};

// from authntic.idl
	[
		uuid(955A131A-731F-11D1-9082-00C04FD91EFE),
		helpstring("Authenticate Class")
	]
	coclass Authenticate
	{
		[default] interface IVWAuthenticate;
	};
	[
		uuid(955A131C-731F-11D1-9082-00C04FD91EFE),
		helpstring("Authentication Class")
	]
	coclass Authentication
	{
		[default] interface IAuthentication;
	};


// from vwsysex.idl
	[
		uuid(717B5A84-7267-11d1-959F-00C04FD91F4D),
		helpstring("SystemExemplar Class")
	]
	coclass SystemExemplar
	{
		[default] interface ISystemExemplar;
	};

	[
		uuid(99AD3619-AAB5-11D0-BAE3-00C04FC2CAB1),
		helpstring("Thing Exemplar Class")
	]
	coclass ThingExemplar
	{
		[default] interface IThingExemplar;
	};

	[
		uuid(99AD361D-AAB5-11D0-BAE3-00C04FC2CAB1),
		helpstring("Artifact Exemplar Class")
	]
	coclass ArtifactExemplar
	{
		[default] interface IArtifactExemplar;
	};

	[
		uuid(99AD361F-AAB5-11D0-BAE3-00C04FC2CAB1),
		helpstring("Avatar Exemplar Class")
	]
	coclass AvatarExemplar
	{
		[default] interface IAvatarExemplar;
	};

	[
		uuid(4874AC90-1B87-11d2-AC71-00104B26A373),
		helpstring("Host Exemplar Class")
	]
	coclass HostExemplar
	{
		[default] interface IHostExemplar;
	};

	[
		uuid(99AD3625-AAB5-11D0-BAE3-00C04FC2CAB1),
		helpstring("Portal Exemplar Class")
	]
	coclass PortalExemplar
	{
		[default] interface IPortalExemplar;
	};
	[
		uuid(FFA01B40-9F4C-11d1-80E8-00C04FC2A129),
		helpstring("InterWorldPortal Exemplar Class")
	]
	coclass IWPortalExemplar
	{
		[default] interface IIWPortalExemplar;
	};

	[
		uuid(99AD3627-AAB5-11D0-BAE3-00C04FC2CAB1),
		helpstring("Room Exemplar Class")
	]
	coclass RoomExemplar
	{
		[default] interface IRoomExemplar;
	};

	[
		uuid(4D83E7E0-F47B-11d1-A392-0000F807558D),
		helpstring("StateMachine Exemplar Class")
	]
	coclass StateMachineExemplar
	{
		[default] interface IStateMachineExemplar;
	};

	[
		uuid(2D0F3A43-5CC3-11d2-82F0-00104B26A373),
		helpstring("WebPage Exemplar Class")
	]
	coclass WebPageExemplar
	{
		[default] interface IWebPageExemplar;
	};
};
