package jp.ac.kobe_u.cs.prolog.builtin;
import jp.ac.kobe_u.cs.prolog.lang.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>'$op2'/3</code> defined in builtins.pl<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @author Douglas R. Miles (dmiles@users.sourceforge.net) for Object(s) 
 @version 1.0-dmiles
*/
class PRED_$op2_3 extends PredicateBase {
    static /*Symbol*/Object s1 = makeAtom("[]");
    static /*Symbol*/Object s2 = makeAtom("type", 1);
    static /*Symbol*/Object s3 = makeAtom("list", 1);
    static /*Symbol*/Object s4 = makeAtom("atom");
    static Object[] s5 = {s4};
    static /*Structure*/Object s6 = makeStructure(s3, s5);
    static Object[] s7 = {s6};
    static /*Structure*/Object s8 = makeStructure(s2, s7);
    static /*Symbol*/Object s9 = makeAtom("op", 3);
    static /*IntegerTerm*/Object si10 = makeInteger(3);
    static Predicate _$op2_3_sub_1 = new PRED_$op2_3_sub_1();
    static Predicate _$op2_3_sub_2 = new PRED_$op2_3_sub_2();
    static Predicate _$op2_3_1 = new PRED_$op2_3_1();
    static Predicate _$op2_3_2 = new PRED_$op2_3_2();
    static Predicate _$op2_3_3 = new PRED_$op2_3_3();

    public Object arg1, arg2, arg3;

    public PRED_$op2_3(Object a1, Object a2, Object a3, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        this.cont = cont;
    }

    public PRED_$op2_3(){}

    public void setArgument(Object[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        this.cont = cont;
    }

    public int arity() { return 3; }

    public String nameUQ() { return "$op2"; }

    public void sArg(int i0, Object val) {  switch (i0) {         case 0: arg1 = val;break ;
         case 1: arg2 = val;break ;
         case 2: arg3 = val;break ;
default: newIndexOutOfBoundsException("setarg" , i0 , val);  }   }


    public Object gArg(int i0) {  switch (i0) {         case 0: return arg1;
         case 1: return arg2;
         case 2: return arg3;
default: return newIndexOutOfBoundsException("getarg", i0,null);  }   }


    public String toPrologString(java.util.Collection newParam) {
        return "'$op2'(" + argString(arg1,newParam) + "," + argString(arg2,newParam) + "," + argString(arg3,newParam) + ")";
    }

    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); 
        engine_aregs[1] = arg1;
        engine_aregs[2] = arg2;
        engine_aregs[3] = arg3;
        engine.cont = cont;
        engine.setB0();
        return engine.jtry(_$op2_3_1, _$op2_3_sub_1);
    }
}

class PRED_$op2_3_sub_1 extends PRED_$op2_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.retry(_$op2_3_2, _$op2_3_sub_2);
    }
}

class PRED_$op2_3_sub_2 extends PRED_$op2_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_$op2_3_3);
    }
}

class PRED_$op2_3_1 extends PRED_$op2_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$op2'(A, B, C):-atom(C), !, '$add_operators'([C], A, B)
        Object a1, a2, a3, a4, a5;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        cont = engine.cont;
    // '$op2'(A, B, C):-['$get_level'(D), atom(C), '$cut'(D), '$add_operators'([C], A, B)]
        a4 = engine.makeVariable(this);
        //START inline expansion of $get_level(a(4))
        if (! unify(a4,makeInteger(engine.B0))) {
            return fail(engine);
        }
        //END inline expansion
        //START inline expansion of atom(a(3))
        a3 = deref( a3);
        if (! isAtomTerm(a3)) {
            return fail(engine);
        }
        //END inline expansion
        //START inline expansion of $cut(a(4))
        a4 = deref( a4);
        if (! isCutter/*Integer*/(a4)) {
            throw new IllegalTypeException("integer", a4);
        } else {
            engine.cut(( a4));
        }
        //END inline expansion
        a5 = makeList(a3, s1);
        return exit(engine, new PRED_$add_operators_3(a5, a1, a2, cont));
    }
}

class PRED_$op2_3_2 extends PRED_$op2_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$op2'(A, B, C):-'$op_atom_list'(C, D), !, '$add_operators'(D, A, B)
        Object a1, a2, a3, a4, a5;
        Predicate p1, p2;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        cont = engine.cont;
    // '$op2'(A, B, C):-['$get_level'(D), '$op_atom_list'(C, E), '$cut'(D), '$add_operators'(E, A, B)]
        a4 = engine.makeVariable(this);
        //START inline expansion of $get_level(a(4))
        if (! unify(a4,makeInteger(engine.B0))) {
            return fail(engine);
        }
        //END inline expansion
        a5 = engine.makeVariable(this);
        p1 = new PRED_$add_operators_3(a5, a1, a2, cont);
        p2 = new PRED_$cut_1(a4, p1);
        return exit(engine, new PRED_$op_atom_list_2(a3, a5, p2));
    }
}

class PRED_$op2_3_3 extends PRED_$op2_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$op2'(A, B, C):-illarg(type(list(atom)), op(A, B, C), 3)
        Object a1, a2, a3, a4;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        cont = engine.cont;
    // '$op2'(A, B, C):-[illarg(type(list(atom)), op(A, B, C), 3)]
        Object[] y1 = {a1, a2, a3};
        a4 = makeStructure(s9, y1);
        return exit(engine, new PRED_illarg_3(s8, a4, si10, cont));
    }
}
