package jp.ac.kobe_u.cs.prolog.builtin;
import jp.ac.kobe_u.cs.prolog.lang.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>'$clause_internal0'/3</code> defined in builtins.pl<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @author Douglas R. Miles (dmiles@users.sourceforge.net) for Object(s) 
 @version 1.0-dmiles
*/
class PRED_$clause_internal0_3 extends PredicateBase {
    static /*Symbol*/Object s1 = makeAtom("[]");
    static /*Symbol*/Object s2 = makeAtom(",", 2);
    static Predicate _$clause_internal0_3_var = new PRED_$clause_internal0_3_var();
    static Predicate _$clause_internal0_3_var_1 = new PRED_$clause_internal0_3_var_1();
    static Predicate _$clause_internal0_3_var_2 = new PRED_$clause_internal0_3_var_2();
    static Predicate _$clause_internal0_3_con = new PRED_$clause_internal0_3_con();
    static Predicate _$clause_internal0_3_con_1 = new PRED_$clause_internal0_3_con_1();
    static Predicate _$clause_internal0_3_lis = new PRED_$clause_internal0_3_lis();
    static Predicate _$clause_internal0_3_lis_1 = new PRED_$clause_internal0_3_lis_1();
    static Predicate _$clause_internal0_3_1 = new PRED_$clause_internal0_3_1();
    static Predicate _$clause_internal0_3_2 = new PRED_$clause_internal0_3_2();
    static Predicate _$clause_internal0_3_3 = new PRED_$clause_internal0_3_3();

    public Object arg1, arg2, arg3;

    public PRED_$clause_internal0_3(Object a1, Object a2, Object a3, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        this.cont = cont;
    }

    public PRED_$clause_internal0_3(){}

    public void setArgument(Object[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        this.cont = cont;
    }

    public int arity() { return 3; }

    public String nameUQ() { return "$clause_internal0"; }

    public void sArg(int i0, Object val) {  switch (i0) {         case 0: arg1 = val;break ;
         case 1: arg2 = val;break ;
         case 2: arg3 = val;break ;
default: newIndexOutOfBoundsException("setarg" , i0 , val);  }   }


    public Object gArg(int i0) {  switch (i0) {         case 0: return arg1;
         case 1: return arg2;
         case 2: return arg3;
default: return newIndexOutOfBoundsException("getarg", i0,null);  }   }


    public String toPrologString(java.util.Collection newParam) {
        return "'$clause_internal0'(" + argString(arg1,newParam) + "," + argString(arg2,newParam) + "," + argString(arg3,newParam) + ")";
    }

    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); 
        engine_aregs[1] = arg1;
        engine_aregs[2] = arg2;
        engine_aregs[3] = arg3;
        engine.cont = cont;
        engine.setB0();
        return engine.switch_on_term(_$clause_internal0_3_var, _$clause_internal0_3_3, _$clause_internal0_3_3, _$clause_internal0_3_con, _$clause_internal0_3_3, _$clause_internal0_3_lis);
    }
}

class PRED_$clause_internal0_3_var extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.jtry(_$clause_internal0_3_1, _$clause_internal0_3_var_1);
    }
}

class PRED_$clause_internal0_3_var_1 extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.retry(_$clause_internal0_3_2, _$clause_internal0_3_var_2);
    }
}

class PRED_$clause_internal0_3_var_2 extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_$clause_internal0_3_3);
    }
}

class PRED_$clause_internal0_3_con extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.jtry(_$clause_internal0_3_1, _$clause_internal0_3_con_1);
    }
}

class PRED_$clause_internal0_3_con_1 extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_$clause_internal0_3_3);
    }
}

class PRED_$clause_internal0_3_lis extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.jtry(_$clause_internal0_3_2, _$clause_internal0_3_lis_1);
    }
}

class PRED_$clause_internal0_3_lis_1 extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_$clause_internal0_3_3);
    }
}

class PRED_$clause_internal0_3_1 extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$clause_internal0'([], A, B):-fail
        Object a1, a2, a3;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        cont = engine.cont;
    // '$clause_internal0'([], A, B):-[fail]
        a1 = deref( a1);
        if (isAtomTerm(a1)){
            if (! prologEquals(a1,s1))
                return fail(engine);
        } else if (isVariable(a1)){
             bind(/*VAR*/ a1,s1);
        } else {
            return fail(engine);
        }
        //START inline expansion of fail
        return fail(engine);
        //END inline expansion
    }
}

class PRED_$clause_internal0_3_2 extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$clause_internal0'([ (A, B)], A, B):-!
        Object a1, a2, a3, a4, a5, a6;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        cont = engine.cont;
    // '$clause_internal0'([ (A, B)], A, B):-['$neck_cut']
        a1 = deref( a1);
        if (isListTerm(a1)){
            Object[] args = consArgs(a1);
            a4 = args[0];
            if (!unify( s1,args[1]))
                return fail(engine);
        } else if (isVariable(a1)){
            a4 = engine.makeVariable(this);
             bind(a1,makeList(a4, s1));
        } else {
            return fail(engine);
        }
        a4 = deref( a4);
        if (isCompound(a4)){
            if (!functorOf( s2,a4))
                return fail(engine);
            Object[] args = args(a4);
            a5 = args[0];
            a6 = args[1];
        } else if (isVariable(a4)){
            a5 = engine.makeVariable(this);
            a6 = engine.makeVariable(this);
            Object[] args = {a5, a6};
            bind(/*VAR*/ a4,makeStructure(s2, args));
        } else {
            return fail(engine);
        }
        if (! unify(a5,a2))
            return fail(engine);
        if (! unify(a6,a3))
            return fail(engine);
        //START inline expansion of $neck_cut
        engine.neckCut();
        //END inline expansion
        return exit(engine,cont);
    }
}

class PRED_$clause_internal0_3_3 extends PRED_$clause_internal0_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$clause_internal0'(A, B, C):-'$builtin_member'((B, C), A)
        Object a1, a2, a3, a4;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        cont = engine.cont;
    // '$clause_internal0'(A, B, C):-['$builtin_member'((B, C), A)]
        Object[] y1 = {a2, a3};
        a4 = makeStructure(s2, y1);
        return exit(engine, new PRED_$builtin_member_2(a4, a1, cont));
    }
}
