package jp.ac.kobe_u.cs.prolog.builtin;
import jp.ac.kobe_u.cs.prolog.lang.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>'$dummy_29_builtins.pl'/5</code> defined in builtins.pl<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @author Douglas R. Miles (dmiles@users.sourceforge.net) for Object(s) 
 @version 1.0-dmiles
*/
class PRED_$dummy_29_builtins$002Epl_5 extends PredicateBase {
    static /*Symbol*/Object s1 = makeAtom("type_error", 4);
    static /*Symbol*/Object s2 = makeAtom("instantiation_error", 2);
    static Predicate _$dummy_29_builtins$002Epl_5_sub_1 = new PRED_$dummy_29_builtins$002Epl_5_sub_1();
    static Predicate _$dummy_29_builtins$002Epl_5_1 = new PRED_$dummy_29_builtins$002Epl_5_1();
    static Predicate _$dummy_29_builtins$002Epl_5_2 = new PRED_$dummy_29_builtins$002Epl_5_2();

    public Object arg1, arg2, arg3, arg4, arg5;

    public PRED_$dummy_29_builtins$002Epl_5(Object a1, Object a2, Object a3, Object a4, Object a5, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        arg4 = a4;
        arg5 = a5;
        this.cont = cont;
    }

    public PRED_$dummy_29_builtins$002Epl_5(){}

    public void setArgument(Object[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        arg4 = args[3];
        arg5 = args[4];
        this.cont = cont;
    }

    public int arity() { return 5; }

    public String nameUQ() { return "$dummy_29_builtins.pl"; }

    public void sArg(int i0, Object val) {  switch (i0) {         case 0: arg1 = val;break ;
         case 1: arg2 = val;break ;
         case 2: arg3 = val;break ;
         case 3: arg4 = val;break ;
         case 4: arg5 = val;break ;
default: newIndexOutOfBoundsException("setarg" , i0 , val);  }   }


    public Object gArg(int i0) {  switch (i0) {         case 0: return arg1;
         case 1: return arg2;
         case 2: return arg3;
         case 3: return arg4;
         case 4: return arg5;
default: return newIndexOutOfBoundsException("getarg", i0,null);  }   }


    public String toPrologString(java.util.Collection newParam) {
        return "'$dummy_29_builtins.pl'(" + argString(arg1,newParam) + "," + argString(arg2,newParam) + "," + argString(arg3,newParam) + "," + argString(arg4,newParam) + "," + argString(arg5,newParam) + ")";
    }

    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); 
        engine_aregs[1] = arg1;
        engine_aregs[2] = arg2;
        engine_aregs[3] = arg3;
        engine_aregs[4] = arg4;
        engine_aregs[5] = arg5;
        engine.cont = cont;
        engine.setB0();
        return engine.jtry(_$dummy_29_builtins$002Epl_5_1, _$dummy_29_builtins$002Epl_5_sub_1);
    }
}

class PRED_$dummy_29_builtins$002Epl_5_sub_1 extends PRED_$dummy_29_builtins$002Epl_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_$dummy_29_builtins$002Epl_5_2);
    }
}

class PRED_$dummy_29_builtins$002Epl_5_1 extends PRED_$dummy_29_builtins$002Epl_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$dummy_29_builtins.pl'(A, B, C, D, E):-nonvar(D), !, E=type_error(B, C, A, D)
        Object a1, a2, a3, a4, a5, a6, a7;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        a4 = engine_aregs[4];
        a5 = engine_aregs[5];
        cont = engine.cont;
    // '$dummy_29_builtins.pl'(A, B, C, D, E):-['$get_level'(F), nonvar(D), '$cut'(F), '$unify'(E, type_error(B, C, A, D))]
        a6 = engine.makeVariable(this);
        //START inline expansion of $get_level(a(6))
        if (! unify(a6,makeInteger(engine.B0))) {
            return fail(engine);
        }
        //END inline expansion
        //START inline expansion of nonvar(a(4))
        a4 = deref( a4);
        if (isVariable(a4)) {
            return fail(engine);
        }
        //END inline expansion
        //START inline expansion of $cut(a(6))
        a6 = deref( a6);
        if (! isCutter/*Integer*/(a6)) {
            throw new IllegalTypeException("integer", a6);
        } else {
            engine.cut(( a6));
        }
        //END inline expansion
        Object[] y1 = {a2, a3, a1, a4};
        a7 = makeStructure(s1, y1);
        //START inline expansion of $unify(a(5), a(7))
        if (! unify(a5,a7)) {
            return fail(engine);
        }
        //END inline expansion
        return exit(engine,cont);
    }
}

class PRED_$dummy_29_builtins$002Epl_5_2 extends PRED_$dummy_29_builtins$002Epl_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$dummy_29_builtins.pl'(A, B, C, D, E):-E=instantiation_error(B, C)
        Object a1, a2, a3, a4, a5, a6;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        a4 = engine_aregs[4];
        a5 = engine_aregs[5];
        cont = engine.cont;
    // '$dummy_29_builtins.pl'(A, B, C, D, E):-['$unify'(E, instantiation_error(B, C))]
        Object[] y1 = {a2, a3};
        a6 = makeStructure(s2, y1);
        //START inline expansion of $unify(a(5), a(6))
        if (! unify(a5,a6)) {
            return fail(engine);
        }
        //END inline expansion
        return exit(engine,cont);
    }
}
