package jp.ac.kobe_u.cs.prolog.builtin;
import jp.ac.kobe_u.cs.prolog.lang.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>'$write_term_op'/8</code> defined in builtins.pl<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @author Douglas R. Miles (dmiles@users.sourceforge.net) for Object(s) 
 @version 1.0-dmiles
*/
class PRED_$write_term_op_8 extends PredicateBase {
    static /*Symbol*/Object s1 = makeAtom("punct");
    static /*Symbol*/Object s2 = makeAtom("(");
    static /*Symbol*/Object s3 = makeAtom(")");
    static Predicate _$write_term_op_8_sub_1 = new PRED_$write_term_op_8_sub_1();
    static Predicate _$write_term_op_8_1 = new PRED_$write_term_op_8_1();
    static Predicate _$write_term_op_8_2 = new PRED_$write_term_op_8_2();

    public Object arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8;

    public PRED_$write_term_op_8(Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        arg4 = a4;
        arg5 = a5;
        arg6 = a6;
        arg7 = a7;
        arg8 = a8;
        this.cont = cont;
    }

    public PRED_$write_term_op_8(){}

    public void setArgument(Object[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        arg4 = args[3];
        arg5 = args[4];
        arg6 = args[5];
        arg7 = args[6];
        arg8 = args[7];
        this.cont = cont;
    }

    public int arity() { return 8; }

    public String nameUQ() { return "$write_term_op"; }

    public void sArg(int i0, Object val) {  switch (i0) {         case 0: arg1 = val;break ;
         case 1: arg2 = val;break ;
         case 2: arg3 = val;break ;
         case 3: arg4 = val;break ;
         case 4: arg5 = val;break ;
         case 5: arg6 = val;break ;
         case 6: arg7 = val;break ;
         case 7: arg8 = val;break ;
default: newIndexOutOfBoundsException("setarg" , i0 , val);  }   }


    public Object gArg(int i0) {  switch (i0) {         case 0: return arg1;
         case 1: return arg2;
         case 2: return arg3;
         case 3: return arg4;
         case 4: return arg5;
         case 5: return arg6;
         case 6: return arg7;
         case 7: return arg8;
default: return newIndexOutOfBoundsException("getarg", i0,null);  }   }


    public String toPrologString(java.util.Collection newParam) {
        return "'$write_term_op'(" + argString(arg1,newParam) + "," + argString(arg2,newParam) + "," + argString(arg3,newParam) + "," + argString(arg4,newParam) + "," + argString(arg5,newParam) + "," + argString(arg6,newParam) + "," + argString(arg7,newParam) + "," + argString(arg8,newParam) + ")";
    }

    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); 
        engine_aregs[1] = arg1;
        engine_aregs[2] = arg2;
        engine_aregs[3] = arg3;
        engine_aregs[4] = arg4;
        engine_aregs[5] = arg5;
        engine_aregs[6] = arg6;
        engine_aregs[7] = arg7;
        engine_aregs[8] = arg8;
        engine.cont = cont;
        engine.setB0();
        return engine.jtry(_$write_term_op_8_1, _$write_term_op_8_sub_1);
    }
}

class PRED_$write_term_op_8_sub_1 extends PRED_$write_term_op_8 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_$write_term_op_8_2);
    }
}

class PRED_$write_term_op_8_1 extends PRED_$write_term_op_8 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$write_term_op'(A, B, C, D, E, punct, F, G):-current_op(H, B, A), H>D, !, '$write_space_if_needed'(E, punct, G), put_char(G, '('), '$write_term_op1'(A, B, C, H, punct, I, F, G), put_char(G, ')')
        Object a1, a2, a3, a4, a5, a6, a7, a8, a9, a10;
        Predicate p1, p2, p3, p4, p5, p6;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        a4 = engine_aregs[4];
        a5 = engine_aregs[5];
        a6 = engine_aregs[6];
        a7 = engine_aregs[7];
        a8 = engine_aregs[8];
        cont = engine.cont;
    // '$write_term_op'(A, B, C, D, E, punct, F, G):-['$get_level'(H), current_op(I, B, A), '$greater_than'(I, D), '$cut'(H), '$write_space_if_needed'(E, punct, G), put_char(G, '('), '$write_term_op1'(A, B, C, I, punct, J, F, G), put_char(G, ')')]
        a6 = deref( a6);
        if (isAtomTerm(a6)){
            if (! prologEquals(a6,s1))
                return fail(engine);
        } else if (isVariable(a6)){
             bind(/*VAR*/ a6,s1);
        } else {
            return fail(engine);
        }
        a9 = engine.makeVariable(this);
        //START inline expansion of $get_level(a(9))
        if (! unify(a9,makeInteger(engine.B0))) {
            return fail(engine);
        }
        //END inline expansion
        a10 = engine.makeVariable(this);
        p1 = new PRED_put_char_2(a8, s3, cont);
        p2 = new PRED_$write_term_op1_8(a1, a2, a3, a10, s1, engine.makeVariable(this), a7, a8, p1);
        p3 = new PRED_put_char_2(a8, s2, p2);
        p4 = new PRED_$write_space_if_needed_3(a5, s1, a8, p3);
        p5 = new PRED_$cut_1(a9, p4);
        p6 = new PRED_$greater_than_2(a10, a4, p5);
        return exit(engine, new PRED_current_op_3(a10, a2, a1, p6));
    }
}

class PRED_$write_term_op_8_2 extends PRED_$write_term_op_8 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$write_term_op'(A, B, C, D, E, F, G, H):-current_op(I, B, A), '$write_term_op1'(A, B, C, I, E, F, G, H)
        Object a1, a2, a3, a4, a5, a6, a7, a8, a9;
        Predicate p1;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        a4 = engine_aregs[4];
        a5 = engine_aregs[5];
        a6 = engine_aregs[6];
        a7 = engine_aregs[7];
        a8 = engine_aregs[8];
        cont = engine.cont;
    // '$write_term_op'(A, B, C, D, E, F, G, H):-[current_op(I, B, A), '$write_term_op1'(A, B, C, I, E, F, G, H)]
        a9 = engine.makeVariable(this);
        p1 = new PRED_$write_term_op1_8(a1, a2, a3, a9, a5, a6, a7, a8, cont);
        return exit(engine, new PRED_current_op_3(a9, a2, a1, p1));
    }
}
