package jp.ac.kobe_u.cs.prolog.builtin;
import jp.ac.kobe_u.cs.prolog.lang.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>read_token/2</code> defined in builtins.pl<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @author Douglas R. Miles (dmiles@users.sourceforge.net) for Object(s) 
 @version 1.0-dmiles
*/
class PRED_read_token_2 extends PredicateBase {
    static /*Symbol*/Object s1 = makeAtom("[]");

    public Object arg1, arg2;

    public PRED_read_token_2(Object a1, Object a2, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        this.cont = cont;
    }

    public PRED_read_token_2(){}

    public void setArgument(Object[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        this.cont = cont;
    }

    public int arity() { return 2; }

    public String nameUQ() { return "read_token"; }

    public void sArg(int i0, Object val) {  switch (i0) {         case 0: arg1 = val;break ;
         case 1: arg2 = val;break ;
default: newIndexOutOfBoundsException("setarg" , i0 , val);  }   }


    public Object gArg(int i0) {  switch (i0) {         case 0: return arg1;
         case 1: return arg2;
default: return newIndexOutOfBoundsException("getarg", i0,null);  }   }


    public String toPrologString(java.util.Collection newParam) {
        return "'read_token'(" + argString(arg1,newParam) + "," + argString(arg2,newParam) + ")";
    }

    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); 
    // read_token(A, B):-'$read_token0'(A, C, D), '$read_token1'([C], D, B)
        engine.setB0();
        Object a1, a2, a3, a4, a5;
        Predicate p1;
        a1 = arg1;
        a2 = arg2;
    // read_token(A, B):-['$read_token0'(A, C, D), '$read_token1'([C], D, B)]
        a3 = engine.makeVariable(this);
        a4 = engine.makeVariable(this);
        a5 = makeList(a3, s1);
        p1 = new PRED_$read_token1_3(a5, a4, a2, cont);
        return exit(engine, new PRED_$read_token0_3(a1, a3, a4, p1));
    }
}
