// Copyright © 2000 Microsoft Corporation.  All rights reserved.
// In installing/viewing this source code, you agree to the terms of the
// Microsoft Research Source License (MSRSL) included in the root of this source tree
// and available from http://www.vworlds.org/license.asp.

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vwsystem.rc
//
#define IDS_VWCLIENT_DESC               1
#define IDS_WORLD_DESC                  2
#define IDS_VECTOR_DESC                 3
#define IDS_VWADMIN_DESC                3
#define IDS_PROPLIST_DESC               4
#define IDS_PROPMAP_DESC                5
#define IDS_UNKNOWN_TYPE                6
#define IDS_VECTOR_TYPE                 7
#define IDS_PROPLIST_TYPE               8
#define IDS_PROPMAP_TYPE                9
#define IDS_THING_DESC                  10
#define IDS_THING_TYPE                  11
#define IDS_NAME_PROP                   12
#define IDS_THINGDEF_DESC               13
#define IDS_LOCATION_PROP               14
#define IDS_CONTAINER_PROP              14
#define IDS_OWNER_PROP                  15
#define IDS_VWSERVER_DESC               16
#define IDS_EDGE_DESC                   17
#define IDS_COMMODULE_DESC              18
#define IDS_SCRIPTMODULE_DESC           19
#define IDS_VWCOMM_DESC                 20
#define IDS_EDGECYCLE_DESC              21
#define IDS_AUTHENTICATION_PROP         21
#define IDS_SELF_EVENT                  22
#define IDS_PEER_EVENT                  23
#define IDS_PARENT_EVENT                24
#define IDS_CHILD_EVENT                 25
#define IDS_CONTENTS_PROP               26
#define IDS_ENTER_EVENT                 27
#define IDS_LEAVE_EVENT                 28
#define IDS_VWSTATMGR_DESC              29
#define IDS_METHOD_DESC                 30
#define IDS_METHOD_TYPE                 31
#define IDS_DESCRIPTION_PROP            32
#define IDS_DESCRIPTION_DEFAULT         33
#define IDS_WORLD_TYPE                  34
#define IDS_MARSHBUF_DESC               35
#define IDS_UNMARSHBUF_DESC             36
#define IDS_CONNECTION_PROP             37
#define IDS_CONNECT_EVENT               38
#define IDS_DISCONNECT_EVENT            39
#define IDS_PROPCHANGE_ON               40
#define IDS_PROPERTYSECURITY_DESC       41
#define IDS_COMMODULE_TYPE              42
#define IDS_SCRIPTMODULE_TYPE           43
#define IDS_PROPCHANGE_CHANGED          44
#define IDS_CREATE_EVENT                45
#define IDS_DESTROY_EVENT               46
#define IDS_SYSCONNECT_EVENT            47
#define IDS_SYSDISCONNECT_EVENT         48
#define IDS_CURRENTID_PROP              49
#define IDS_ROOM_TYPE                   50
#define IDS_AVATAR_TYPE                 51
#define IDS_MOVETO_METHOD               52
#define IDS_AVATARS_PROP                53
#define IDS_EXEMPLARS_PROP              54
#define IDS_MODULES_PROP                55
#define IDS_WIELDED_PROP                56
#define IDS_EDGECYCLEBUILDER_DESC       57
#define IDS_SYSTEMCREATE_EVENT          57
#define IDS_CELL_DESC                   58
#define IDS_SYSTEMDESTROY_EVENT         58
#define IDS_MENUITEM_DESC               59
#define IDS_MENUITEM_TYPE               60
#define IDS_MENU_DESC                   61
#define IDS_MENU_TYPE                   62
#define IDS_VECTOROBJECT_DESC           63
#define IDS_PROPCHANGE_ACCESS           63
#define IDS_INETFILEMANAGER_DESC        64
#define IDS_VWGEOMETRYOBJECT_DESC       65
#define IDS_ADDDEFAULTKEYS_METHOD       65
#define IDS_VWGEOMETRY_TYPE             66
#define IDS_VWGEOMETRYSPRITE_DESC       67
#define IDS_VWGEOMETRYSP_TYPE           68
#define IDS_VWINTERSECTDATAOBJECT_DESC  69
#define IDS_VWANIMATOR_DESC             70
#define IDS_VWANIMATION_DESC            71
#define IDS_VWSOUND_DESC                72
#define IDS_SOUNDBUFFER_DESC            73
#define IDS_SOUND3DBUFFER_DESC          74
#define IDS_VWHTML_DESC                 75
#define IDS_VWHTMLHELPER_DESC           76
#define IDS_VWFRAMEOBJECT_DESC          77
#define IDS_MODULE_TYPE                 78
#define IDS_VWNAVIGATIONTOOL2D_DESC     79
#define IDS_ROOMDEF_DESC                80
#define IDS_GEOMETRYDEF_DESC            81
#define IDS_TELL_METHOD                 82
#define IDS_VWNAVIGATIONTOOL3D_DESC     83
#define IDS_VWRENDER3D_DESC             84
#define IDS_ANNOUNCE_METHOD             85
#define IDS_VWRENDER2D_DESC             86
#define IDS_VWRENDERROOT_DESC           87
#define IDS_SYSTEMENTER_EVENT           88
#define IDS_SYSTEMLEAVE_EVENT           89
#define IDS_VWNAVIGATIONTOOL2D3D_DESC   90
#define IDS_VWPKTOOL_DESC               92
#define IDS_TELL_EVENT                  93
#define IDS_PEERTELL_METHOD             94
#define IDS_PASSWORD_PROP               95
#define IDS_ISCONNECTED_PROP            96
#define IDS_INVOKEMETHODFAILED_METHOD   97
#define IDS_ACTIVATE_EVENT              98
#define IDS_DEACTIVATE_EVENT            99
#define IDS_PROJNAME                    100
#define IDS_VWODB_DESC                  101
#define IDR_DSERV                       102
#define IDS_CELL_TYPE                   102
#define IDS_SYSTEMACTIVATE_EVENT        102
#define IDS_EDGE_TYPE                   103
#define IDS_SYSTEMDEACTIVATE_EVENT      103
#define IDS_EDGECYCLE_TYPE              104
#define IDS_EDGECYCLEBUILDER_TYPE       105
#define IDS_VWINTERSECTDATAOBJECT_TYPE  106
#define IDS_VWFRAMEOBJECT_TYPE          107
#define IDS_ISFERTILE_PROP              108
#define IDS_ISOPEN_PROP                 109
#define IDS_ISNOTICEABLE_PROP           110
#define IDS_ISEXEMPLAR_PROP             111
#define IDS_VWGEOMETRYARTICULATED_DESC  112
#define IDS_VWGEOMETRYARTICULATED_TYPE  113
#define IDS_VWGEOMETRYCACHEOBJECT_DESC  114
#define IDS_ISCLONEABLE_PROP            115
#define IDS_GUIDS_PROP                  116
#define IDR_VWCLIENTOCX                 117
#define IDS_GUID_PROP                   117
#define IDS_OCXPROXY_TYPE               118
#define IDS_OCXPROXY_DESC               119
#define IDS_PROFILE_TYPE                120
#define IDS_AVATARPROFILE_DESC          121
#define IDS_PROFILEDATA_TYPE            122
#define IDS_AVATARPROFILEDATA_DESC      123
#define IDC_USER                        201
#define IDC_EDIT_PASS                   201
#define IDC_PASSWORD                    202
#define IDC_DOMAIN                      203
#define IDD_LOGON                       203
#define IDR_VWSYSEX                     210
#define IDR_ARTIFACTEXEMPLAR            211
#define IDR_THINGEXEMPLAR               212
#define IDR_PORTALEXEMPLAR              213
#define IDR_ROOMEXEMPLAR                214
#define IDR_REGISTRY4                   215
#define IDR_AVATAREXEMPLAR              215
#define IDR_REGISTRY5                   219
#define IDR_AUTHENTICATION              222
#define IDR_REGISTRY2                   223
#define IDR_AUTHENTICATE                223
#define IDR_REGISTRY1                   225
#define IDR_IWPORTALEXEMPLAR            225
#define IDR_STATEMACHINEEXEMPLAR        226
#define IDR_RGS1                        227
#define IDR_HOSTEXEMPLAR                231
#define IDD_PASSWORD                    232
#define IDR_WEBPAGEEXEMPLAR             235
#define IDR_AVATARPROFILE               510
#define IDR_DLTHREAD                    511
#define IDS_INVOKEEXCEPTION             0x201
#define IDS_FILEEXCEPTION               0x202
#define IDS_FILEREADERROR               0x203
#define IDS_INVALIDMODULE               0x204
#define IDS_COLLECTIONERROR             0x205
#define IDS_WRONGPROPERTYTYPE           0x206
#define IDS_UNKNOWNTYPE                 0x207
#define IDS_INVALIDPROPERTYLIST         0x208
#define IDS_PROPERTYEXISTS              0x209
#define IDS_INVALIDPROPERTYMAP          0x020A
#define IDS_PROPERTYNOTEXIST            0x020c
#define IDS_METHODEXISTS                0x020D
#define IDS_METHODNOTEXIST              0x020f
#define IDS_INVALIDMETHOD               0x0210
#define IDS_INVALIDMETHODMAP            0x0211
#define IDS_CONNECTIONERROR             0x0212
#define IDS_INVALIDCREATUREMAP          0x0213
#define IDS_EXEMPLAREXISTS              0x0214
#define IDS_INVALIDOBJECT               0x0215
#define IDS_EXEMPLARNOTEXIST            0x0216
#define IDS_INVALIDEXEMPLARMAP          0x0217
#define IDS_CREATUREEXISTS              0x0218
#define IDS_INVALIDTOOLMAP              0x0219
#define IDS_INVALIDMODULEMAP            0x021A
#define IDS_STUBOBJECT                  0x021B
#define IDS_UNKNOWNPROPERTYTYPE         0x021C
#define IDS_UNKNOWNMESSAGETYPE          0x021D
#define IDS_MODULEEXISTS                0x021E
#define IDS_MODULENOTEXIST              0x021F
#define IDS_TOOLEXISTS                  0x0220
#define IDS_TOOLNOTEXIST                0x0221
#define IDS_INVALIDMODULETYPE           0x0222
#define IDS_UNKNOWNPROGID               0x0223
#define IDS_INVALIDCONNECTION           0x0224
#define IDS_INTERFACENOTSUPPORTED       0x0225
#define IDS_INVALIDTRACELEVEL           0x0226
#define IDS_COLLECTIONLEVEL             0x0227
#define IDS_PERMISSION_DENIED           0x0228
#define IDS_SYNTAX_ERROR                0x0229
#define IDS_UNKNOWNTRACECOMPONENT       0x022A
#define IDS_ALREADYCONNECTED            0x022B
#define IDS_OBJECTNOTFOUND              0x022C
#define IDS_UNKNOWNCLSIDINDEX           0x022D
#define IDS_INVALIDLISTINDEX            0x022E
#define IDS_EMPTYPROPERTYLIST           0x022F
#define IDS_TYPE_MISMATCH               0x0230
#define IDS_INVALIDDEFAULTSCRIPT        0x0231
#define IDS_INVALIDWORLD                562
#define IDS_INVALIDBITSTATE             563
#define IDS_EVENTABORTED                564
#define IDS_EXEMPLARNOTFERTILE          565
#define IDS_INVALIDPROPERTYNAME         566
#define IDS_INVALIDEXEMPLARTYPE         567
#define IDS_INVALIDINSTANCENAME         568
#define IDS_INVALIDSCRIPTENGINE         569
#define IDS_UNKNOWNSCRIPTERROR          570
#define IDS_INVALIDCONTAINER            571
#define IDS_AVATARNOTEXIST              572
#define IDS_INVALIDSECURITY             573
#define IDS_ONLYRECONNECTFROMCLIENT     574
#define IDS_OBJECTNOTEXEMPLAR           575
#define IDS_INSTANCENOTCLONEABLE        576
#define IDS_EXEMPLARNOTCLONEABLE        577
#define IDS_INVALIDURLFORMAT            578
#define IDS_ONLYSERVERSIDE              580
#define IDS_INVALIDPARENT               0x245
#define IDS_INVALIDWORLDREGISTRY        582
#define IDS_PROCESSMSGEXCEPTION         583
#define IDS_INVALIDBSTRSIZE             0x248
#define IDS_ALREADYDESTROYED            585
#define IDS_INVALIDEXEMPLAR             586
#define IDS_INVALIDPASSWORD             587
#define IDS_CANTDESTROYUSER             588
#define IDS_CANTDESTROYCONTAINER        589
#define IDS_CANTDESTROYROOM             590
#define IDS_INVALIDCONTENTPATH          591
#define IDS_INVALIDCOSTUMEPATH          592
#define IDS_INVALIDAVATARGRAPHICSPATH   592
#define IDS_INVALIDAVATARPATH           593
#define IDS_INVALIDHTMLPATH             594
#define IDS_INVALIDPROFILE              594
#define IDS_INVALIDHELPPATH             595
#define IDS_INVALIDWORLDPATH            596
#define IDS_CANTDESTROYAVATAR           597
#define IDS_INVALIDDSURL                598
#define IDS_NOTCLIENTMODULE             599
#define IDS_NOTSERVERMODULE             600
#define IDS_NOTSAFEFORSCRIPTING         601
#define IDS_INCORRECTPROFILEVERSION     602
#define IDS_INVALIDPROFILEVERSION       602
#define IDS_INVALIDCLIENTVERSION        603
#define IDS_SCRIPTNOTFOUND              604
#define IDS_COMPONENTNOTFOUND           605
#define IDS_INVALIDONACCESSMETHOD       606
#define IDS_EXTERNALCALLONLY            607
#define IDS_EXCEEDEDOBJECTQUOTA         608
#define IDS_CANTDESTROYEXEMPLAR         609
#define IDS_INVALIDMETHODNAME           610
#define IDS_INVALIDWORLDNAME            611
#define IDS_INVALIDAVATARNAME           612
#define IDS_INVALIDNAME                 613
#define IDS_NORECONNECTTOSAMEWORLD      614
#define IDS_INVALIDMETHODPERMISSIONS    615
#define IDS_INVALIDDIRECTORYSERVICEPAGE 616
#define IDS_PARSESCRIPTERROR            617
#define IDS_MODULESHUTDOWN              618
#define IDS_CANTCREATEAVATAR            619
#define IDS_RUNTIMESCRIPTERROR          620
#define IDS_COPYINGNOTSUPPORTED         622
#define IDS_CLIENTALREADYCONNECTED      0x301
#define IDS_WINDOWCREATIONFAILURE       0x302
#define IDS_POSTMESSAGEFAILURE          771
#define IDS_INVALIDREPLYFROMSERVER      772
#define IDS_INVALIDDATABASENAME         773
#define IDS_CONNECTFAILED               774
#define IDS_INVALIDKEYMAP               0x380
#define IDS_INVALIDBANNEDOBJECTLIST     897
#define IDS_KEYNOTEXIST                 898
#define IDS_KEYEXISTS                   899
#define IDS_BANNEDOBJECT                900
#define IDS_AVPROF_PERMISSIONDENIED     901
#define IDS_INVALIDOWNER                902
#define IDS_SERVER_OFFLINEWORLD         0x402
#define IDS_SERVER_ALREADY_REGISTERED   1027
#define IDS_DLCOULDNTCONNECT            0x501
#define IDS_DLCOULDNTACCEPT             0x502
#define IDS_DLNOTINITIALIZED            0x503
#define IDS_DLINVALIDCONFIGURATION      0x504
#define IDS_DLUNKNOWNERROR              0x505
#define IDS_DLINVALIDPARAMETER          0x506
#define IDS_DLINTERNALTIMEOUT           0x507
#define IDS_DLERRORDURINGSYNCHWRITE     0x508
#define IDS_DLNOMESSAGES                0x509
#define IDS_CONNECTIONNOTFOUND          0x50A
#define IDS_INVALIDSOCKET               1291
#define IDS_IMPROPERSTATE               1292
#define IDS_WINSOCKERROR                1293
#define IDS_COULDNTINITIALIZE           1294
#define IDS_ALREADYINWRITESYNCH         1295
#define IDS_ALREADYOPEN                 0x601
#define IDS_DBCREATEERROR               1538
#define IDS_DBNOTEXIST                  1539
#define IDS_DBREADERROR                 1540
#define IDS_DBOPENERROR                 1541
#define IDS_INVALIDDBSIGNATURE          1542
#define IDS_OBJECTNOTEXIST              1543
#define IDS_INVALIDDBRECORD             1544
#define IDS_NOTPERSISTMODE              1545
#define IDS_BACKUPFAILED                1546
#define IDS_LOGRECORDTOOLARGE           1547
#define IDS_NOTOPEN                     1548
#define IDS_INVALIDDBNAME               1549
#define IDS_DBALREADYEXIST              1550
#define IDS_NOTINITIALIZED              0x701
#define IDS_ERRORMAPPINGFILE            1794
#define IDS_INVALIDSOUNDFORMAT          1795
#define IDS_VWPORTAL_INVALIDINDEX       3072
#define IDS_VWPORTAL_E_INVALIDDESTINATION 3074
#define IDS_VWPORTAL_UNKNOWN            3075
#define IDS_VWAVATAR_NODEFAULTROOMORPORTAL 3088
#define IDS_VWAVATAR_NOPROFILE          3089
#define IDS_VWAVATAR_WHISPERNOTALLOWED  3090
#define IDS_VWHOST_NOTAHOST             3104
#define IDS_VWHOST_CANTLOGOFFWIZARD     3105
#define IDS_VWTHING_MOVEINTOPOLICYDENIED 3120
#define IDS_VWTHING_E_ACCEPTLEAVEDENIED 3121
#define IDS_VWTHING_ALLOWLEAVEDENIED    3122
#define IDS_VWTHING_ACCEPTENTERDENIED   3123
#define IDS_VWTHING_ALLOWENTERDENIED    3124
#define IDS_VWTHING_TAKENOTINCONTAINER  3125
#define IDS_VWTHING_DROPNOTINCONTENTS   3126
#define IDS_VWTHING_TAKEPERMISSIONDENIED 3127
#define IDW_VWTHING_UNKNOWN             3128
#define IDS_VWTHING_NOSECURITYONSERVER  3129
#define IDS_VWTHING_NOSECURITYFORUNKNOWNUSER 3130
#define IDS_VWTHING_NOTCLIENTPROPERTY   3131
#define IDS_VWIWPORTAL_E_NODESTINATION  3152
#define IDS_VWIWPORTAL_E_INVALIDDESTINATION 3153
#define IDS_VWIWPORTAL_E_RECONNECTFAILED 3154
#define IDS_VWCORE_FILECOPYERROR        3168
#define IDS_VWCORE_FILEUPLOADERROR      3168
#define IDS_VWCORE_NOTAWIZARD           3169
#define IDS_VWCORE_NOTANAVATAR          3170
#define IDS_VWCORE_NOTAHOST             3171
#define IDS_FILENOTFOUND                0xd01
#define IDS_PATHNOTFOUND                3330
#define IDS_INVALIDROOTURL              3330
#define IDS_CACHEISEMPTY                3331
#define IDS_COMMITFAILED                3332
#define IDS_ANIMATIONNOTEXIST           0x0d81
#define IDS_EMPTY_ATOM                  4999
#define IDS_START_ATOM                  5000
#define IDS_STRING5001                  5001
#define IDS_STRING5002                  5002
#define IDS_STRING5003                  5003
#define IDS_STRING5004                  5004
#define IDS_STRING5005                  5005
#define IDS_STRING5006                  5006
#define IDS_STRING5007                  5007
#define IDS_STRING5008                  5008
#define IDS_STRING5009                  5009
#define IDS_STRING5010                  5010
#define IDS_STRING5011                  5011
#define IDS_STRING5012                  5012
#define IDS_STRING5013                  5013
#define IDS_STRING5014                  5014
#define IDS_STRING5015                  5015
#define IDS_STRING5016                  5016
#define IDS_STRING5017                  5017
#define IDS_STRING5018                  5018
#define IDS_STRING5019                  5019
#define IDS_STRING5020                  5020
#define IDS_STRING5021                  5021
#define IDS_STRING5022                  5022
#define IDS_STRING5023                  5023
#define IDS_STRING5024                  5024
#define IDS_STRING5025                  5025
#define IDS_STRING5026                  5026
#define IDS_STRING5027                  5027
#define IDS_STRING5028                  5028
#define IDS_STRING5029                  5029
#define IDS_STRING5030                  5030
#define IDS_STRING5031                  5031
#define IDS_STRING5032                  5032
#define IDS_STRING5033                  5033
#define IDS_STRING5034                  5034
#define IDS_STRING5035                  5035
#define IDS_STRING5036                  5036
#define IDS_STRING5037                  5037
#define IDS_STRING5038                  5038
#define IDS_STRING5039                  5039
#define IDS_STRING5040                  5040
#define IDS_STRING5041                  5041
#define IDS_STRING5042                  5042
#define IDS_STRING5043                  5043
#define IDS_STRING5044                  5044
#define IDS_STRING5045                  5045
#define IDS_STRING5046                  5046
#define IDS_STRING5047                  5047
#define IDS_STRING5048                  5048
#define IDS_STRING5049                  5049
#define IDS_STRING5050                  5050
#define IDS_STRING5051                  5051
#define IDS_STRING5052                  5052
#define IDS_STRING5053                  5053
#define IDS_STRING5054                  5054
#define IDS_STRING5055                  5055
#define IDS_STRING5056                  5056
#define IDS_STRING5057                  5057
#define IDS_STRING5058                  5058
#define IDS_STRING5059                  5059
#define IDS_STRING5060                  5060
#define IDS_STRING5061                  5061
#define IDS_STRING5062                  5062
#define IDS_STRING5063                  5063
#define IDS_STRING5064                  5064
#define IDS_STRING5065                  5065
#define IDS_STRING5066                  5066
#define IDS_STRING5067                  5067
#define IDS_STRING5068                  5068
#define IDS_STRING5069                  5069
#define IDS_STRING5070                  5070
#define IDS_STRING5071                  5071
#define IDS_STRING5072                  5072
#define IDS_STRING5073                  5073
#define IDS_STRING5074                  5074
#define IDS_STRING5075                  5075
#define IDS_STRING5076                  5076
#define IDS_STRING5077                  5077
#define IDS_STRING5078                  5078
#define IDS_STRING5079                  5079
#define IDS_STRING5080                  5080
#define IDS_STRING5081                  5081
#define IDS_STRING5082                  5082
#define IDS_STRING5083                  5083
#define IDS_STRING5084                  5084
#define IDS_STRING5085                  5085
#define IDS_STRING5086                  5086
#define IDS_STRING5087                  5087
#define IDS_STRING5088                  5088
#define IDS_STRING5089                  5089
#define IDS_STRING5090                  5090
#define IDS_STRING5091                  5091
#define IDS_STRING5092                  5092
#define IDS_STRING5093                  5093
#define IDS_STRING5094                  5094
#define IDS_STRING5095                  5095
#define IDS_STRING5096                  5096
#define IDS_STRING5097                  5097
#define IDS_STRING5098                  5098
#define IDS_STRING5099                  5099
#define IDS_STRING5100                  5100
#define IDS_STRING5101                  5101
#define IDS_STRING5102                  5102
#define IDS_STRING5103                  5103
#define IDS_STRING5104                  5104
#define IDS_STRING5105                  5105
#define IDS_STRING5106                  5106
#define IDS_STRING5107                  5107
#define IDS_STRING5108                  5108
#define IDS_STRING5109                  5109
#define IDS_STRING5110                  5110
#define IDS_STRING5111                  5111
#define IDS_STRING5112                  5112
#define IDS_STRING5113                  5113
#define IDS_STRING5114                  5114
#define IDS_STRING5115                  5115
#define IDS_STRING5116                  5116
#define IDS_STRING5117                  5117
#define IDS_STRING5118                  5118
#define IDS_STRING5119                  5119
#define IDS_STRING5120                  5120

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         202
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
