#!/bin/bash

. ../../bin/setpaths

# SWI-Prolog Modules
# javart.pl   alarm.pl

    
# System dependant
# moo_ciao.pl 
# moo_bprolog.pl  
# moo_swiprolog_unix.pl  
# moo_swiprolog_win32.pl 

cat moo_$1.pl moo_header.pl  moo_globalisms.pl  moo_threads.pl  moo_utility.pl    moo_generation.pl    moo_httpd.pl  moo_insert.pl  moo_java.pl  moo_markup.pl  moo_metabuiltins.pl  moo_nfs.pl   moo_algebra.pl moo_english.pl  moo_api.pl   moo_belief.pl   moo_browser.pl  moo_chat.pl   moo_cmdline.pl  moo_compiler.pl  moo_cycl.pl  moo_database.pl moo_fileutils.pl  moo_motel.pl moo_functionals.pl moo_pttp_xray.pl   moo_reader.pl  moo_sentence.pl  moo_simple.pl  moo_slg_tabling.pl  moo_soap.pl    moo_transitiveclosure.pl  moo_uwdgraphs.pl moo_initialize.pl > start_$1.pl

# moo_csat.pl moo_icl.pl  moo_oprove.pl  moo_tap.pl   
# moo_testing.pl

# Virtual World Components 
# cat  moo_tokenization.pl  moo_apldriver.pl moo_type_template.pl  moo_actx_invokes.pl  moo_dspg.pl moo_espg.pl  moo_event_to_property.pl  moo_goal_threads.pl  moo_planning_datahooks.pl  moo_planning.pl  moo_proquery.pl   moo_sdk.pl    moo_spg.pl moo_vwevents.pl  moo_vwevent_to_method.pl  moo_vwmethods.pl  moo_vwtriggers.pl moo_vb6support.pl  > moo_virtualworld.pl


pl-mt -f start_$1.pl


# Not used
# moo_unused.pl  


