package jp.ac.kobe_u.cs.prolog.builtin;
import jp.ac.kobe_u.cs.prolog.lang.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>'$variants_subset'/5</code> defined in builtins.pl<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @author Douglas R. Miles (dmiles@users.sourceforge.net) for Object(s) 
 @version 1.0-dmiles
*/
class PRED_$variants_subset_5 extends PredicateBase {
    static /*Symbol*/Object s1 = makeAtom("[]");
    static /*Symbol*/Object s2 = makeAtom("+", 2);
    static Predicate _$variants_subset_5_top = new PRED_$variants_subset_5_top();
    static Predicate _fail_0 = new PRED_fail_0();
    static Predicate _$variants_subset_5_var = new PRED_$variants_subset_5_var();
    static Predicate _$variants_subset_5_var_1 = new PRED_$variants_subset_5_var_1();
    static Predicate _$variants_subset_5_var_2 = new PRED_$variants_subset_5_var_2();
    static Predicate _$variants_subset_5_lis = new PRED_$variants_subset_5_lis();
    static Predicate _$variants_subset_5_lis_1 = new PRED_$variants_subset_5_lis_1();
    static Predicate _$variants_subset_5_1 = new PRED_$variants_subset_5_1();
    static Predicate _$variants_subset_5_2 = new PRED_$variants_subset_5_2();
    static Predicate _$variants_subset_5_3 = new PRED_$variants_subset_5_3();

    public Object arg1, arg2, arg3, arg4, arg5;

    public PRED_$variants_subset_5(Object a1, Object a2, Object a3, Object a4, Object a5, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        arg4 = a4;
        arg5 = a5;
        this.cont = cont;
    }

    public PRED_$variants_subset_5(){}

    public void setArgument(Object[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        arg4 = args[3];
        arg5 = args[4];
        this.cont = cont;
    }

    public int arity() { return 5; }

    public String nameUQ() { return "$variants_subset"; }

    public void sArg(int i0, Object val) {  switch (i0) {         case 0: arg1 = val;break ;
         case 1: arg2 = val;break ;
         case 2: arg3 = val;break ;
         case 3: arg4 = val;break ;
         case 4: arg5 = val;break ;
default: newIndexOutOfBoundsException("setarg" , i0 , val);  }   }


    public Object gArg(int i0) {  switch (i0) {         case 0: return arg1;
         case 1: return arg2;
         case 2: return arg3;
         case 3: return arg4;
         case 4: return arg5;
default: return newIndexOutOfBoundsException("getarg", i0,null);  }   }


    public String toPrologString(java.util.Collection newParam) {
        return "'$variants_subset'(" + argString(arg1,newParam) + "," + argString(arg2,newParam) + "," + argString(arg3,newParam) + "," + argString(arg4,newParam) + "," + argString(arg5,newParam) + ")";
    }

    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); 
        engine_aregs[1] = arg1;
        engine_aregs[2] = arg2;
        engine_aregs[3] = arg3;
        engine_aregs[4] = arg4;
        engine_aregs[5] = arg5;
        engine.cont = cont;
        return exit(engine, _$variants_subset_5_top);
    }
}

class PRED_$variants_subset_5_top extends PRED_$variants_subset_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        engine.setB0();
        return engine.switch_on_term(_$variants_subset_5_var, _fail_0, _fail_0, _$variants_subset_5_1, _fail_0, _$variants_subset_5_lis);
    }
}

class PRED_$variants_subset_5_var extends PRED_$variants_subset_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.jtry(_$variants_subset_5_1, _$variants_subset_5_var_1);
    }
}

class PRED_$variants_subset_5_var_1 extends PRED_$variants_subset_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.retry(_$variants_subset_5_2, _$variants_subset_5_var_2);
    }
}

class PRED_$variants_subset_5_var_2 extends PRED_$variants_subset_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_$variants_subset_5_3);
    }
}

class PRED_$variants_subset_5_lis extends PRED_$variants_subset_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.jtry(_$variants_subset_5_2, _$variants_subset_5_lis_1);
    }
}

class PRED_$variants_subset_5_lis_1 extends PRED_$variants_subset_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_$variants_subset_5_3);
    }
}

class PRED_$variants_subset_5_1 extends PRED_$variants_subset_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$variants_subset'([], A, [], [], []):-!
        Object a1, a2, a3, a4, a5;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        a4 = engine_aregs[4];
        a5 = engine_aregs[5];
        cont = engine.cont;
    // '$variants_subset'([], A, [], [], []):-['$neck_cut']
        a1 = deref( a1);
        if (isAtomTerm(a1)){
            if (! prologEquals(a1,s1))
                return fail(engine);
        } else if (isVariable(a1)){
             bind(/*VAR*/ a1,s1);
        } else {
            return fail(engine);
        }
        a3 = deref( a3);
        if (isAtomTerm(a3)){
            if (! prologEquals(a3,s1))
                return fail(engine);
        } else if (isVariable(a3)){
             bind(/*VAR*/ a3,s1);
        } else {
            return fail(engine);
        }
        a4 = deref( a4);
        if (isAtomTerm(a4)){
            if (! prologEquals(a4,s1))
                return fail(engine);
        } else if (isVariable(a4)){
             bind(/*VAR*/ a4,s1);
        } else {
            return fail(engine);
        }
        a5 = deref( a5);
        if (isAtomTerm(a5)){
            if (! prologEquals(a5,s1))
                return fail(engine);
        } else if (isVariable(a5)){
             bind(/*VAR*/ a5,s1);
        } else {
            return fail(engine);
        }
        //START inline expansion of $neck_cut
        engine.neckCut();
        //END inline expansion
        return exit(engine,cont);
    }
}

class PRED_$variants_subset_5_2 extends PRED_$variants_subset_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$variants_subset'([A+B|C], D, [A+B|E], [B|F], G):-'$term_variant'(D, A), !, '$variants_subset'(C, D, E, F, G)
        Object a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13;
        Predicate p1, p2;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        a4 = engine_aregs[4];
        a5 = engine_aregs[5];
        cont = engine.cont;
    // '$variants_subset'([A+B|C], D, [A+B|E], [B|F], G):-['$get_level'(H), '$term_variant'(D, A), '$cut'(H), '$variants_subset'(C, D, E, F, G)]
        a1 = deref( a1);
        if (isListTerm(a1)){
            Object[] args = consArgs(a1);
            a6 = args[0];
            a7 = args[1];
        } else if (isVariable(a1)){
            a6 = engine.makeVariable(this);
            a7 = engine.makeVariable(this);
             bind(a1,makeList(a6, a7));
        } else {
            return fail(engine);
        }
        a6 = deref( a6);
        if (isCompound(a6)){
            if (!functorOf( s2,a6))
                return fail(engine);
            Object[] args = args(a6);
            a8 = args[0];
            a9 = args[1];
        } else if (isVariable(a6)){
            a8 = engine.makeVariable(this);
            a9 = engine.makeVariable(this);
            Object[] args = {a8, a9};
            bind(/*VAR*/ a6,makeStructure(s2, args));
        } else {
            return fail(engine);
        }
        a3 = deref( a3);
        if (isListTerm(a3)){
            Object[] args = consArgs(a3);
            a10 = args[0];
            a11 = args[1];
        } else if (isVariable(a3)){
            a10 = engine.makeVariable(this);
            a11 = engine.makeVariable(this);
             bind(a3,makeList(a10, a11));
        } else {
            return fail(engine);
        }
        a10 = deref( a10);
        if (isCompound(a10)){
            if (!functorOf( s2,a10))
                return fail(engine);
            Object[] args = args(a10);
            if (!unify( a8,args[0]))
                return fail(engine);
            if (!unify( a9,args[1]))
                return fail(engine);
        } else if (isVariable(a10)){
            Object[] args = {a8, a9};
            bind(/*VAR*/ a10,makeStructure(s2, args));
        } else {
            return fail(engine);
        }
        a4 = deref( a4);
        if (isListTerm(a4)){
            Object[] args = consArgs(a4);
            if (!unify( a9,args[0]))
                return fail(engine);
            a12 = args[1];
        } else if (isVariable(a4)){
            a12 = engine.makeVariable(this);
             bind(a4,makeList(a9, a12));
        } else {
            return fail(engine);
        }
        a13 = engine.makeVariable(this);
        //START inline expansion of $get_level(a(13))
        if (! unify(a13,makeInteger(engine.B0))) {
            return fail(engine);
        }
        //END inline expansion
        p1 = new PRED_$variants_subset_5(a7, a2, a11, a12, a5, cont);
        p2 = new PRED_$cut_1(a13, p1);
        return exit(engine, new PRED_$term_variant_2(a2, a8, p2));
    }
}

class PRED_$variants_subset_5_3 extends PRED_$variants_subset_5 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$variants_subset'([A|B], C, D, E, [A|F]):-'$variants_subset'(B, C, D, E, F)
        Object a1, a2, a3, a4, a5, a6, a7, a8;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        a4 = engine_aregs[4];
        a5 = engine_aregs[5];
        cont = engine.cont;
    // '$variants_subset'([A|B], C, D, E, [A|F]):-['$variants_subset'(B, C, D, E, F)]
        a1 = deref( a1);
        if (isListTerm(a1)){
            Object[] args = consArgs(a1);
            a6 = args[0];
            a7 = args[1];
        } else if (isVariable(a1)){
            a6 = engine.makeVariable(this);
            a7 = engine.makeVariable(this);
             bind(a1,makeList(a6, a7));
        } else {
            return fail(engine);
        }
        a5 = deref( a5);
        if (isListTerm(a5)){
            Object[] args = consArgs(a5);
            if (!unify( a6,args[0]))
                return fail(engine);
            a8 = args[1];
        } else if (isVariable(a5)){
            a8 = engine.makeVariable(this);
             bind(a5,makeList(a6, a8));
        } else {
            return fail(engine);
        }
        engine_aregs[1] = a7;
        engine_aregs[2] = a2;
        engine_aregs[3] = a3;
        engine_aregs[4] = a4;
        engine_aregs[5] = a8;
        engine.cont = cont;
        return exit(engine, _$variants_subset_5_top);
    }
}
