package jp.ac.kobe_u.cs.prolog.builtin;
import jp.ac.kobe_u.cs.prolog.lang.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>'$toplvel_loop'/0</code> defined in builtins.pl<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @author Douglas R. Miles (dmiles@users.sourceforge.net) for Object(s) 
 @version 1.0-dmiles
*/
class PRED_$toplvel_loop_0 extends PredicateBase {
    static /*Symbol*/Object s1 = makeAtom("debug");
    static /*Symbol*/Object s2 = makeAtom("| ?- ");

    public PRED_$toplvel_loop_0(Predicate cont) {
        this.cont = cont;
    }

    public PRED_$toplvel_loop_0(){}

    public void setArgument(Object[] args, Predicate cont) {
        this.cont = cont;
    }

    public int arity() { return 0; }

    public String nameUQ() { return "$toplvel_loop"; }

    public void sArg(int i0, Object val) {  switch (i0) {default: newIndexOutOfBoundsException("setarg" , i0 , val);  }   }


    public Object gArg(int i0) {  switch (i0) {default: return newIndexOutOfBoundsException("getarg", i0,null);  }   }


    public String toPrologString(java.util.Collection newParam) {
        return "'$toplvel_loop";
    }

    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); 
    // '$toplvel_loop':-current_prolog_flag(debug, A), '$dummy_25_builtins.pl'(A), '$fast_write'('| ?- '), flush_output
        engine.setB0();
        Object a1;
        Predicate p1, p2, p3;
    // '$toplvel_loop':-[current_prolog_flag(debug, A), '$dummy_25_builtins.pl'(A), '$fast_write'('| ?- '), flush_output]
        a1 = engine.makeVariable(this);
        p1 = new PRED_flush_output_0(cont);
        p2 = new PRED_$fast_write_1(s2, p1);
        p3 = new PRED_$dummy_25_builtins$002Epl_1(a1, p2);
        return exit(engine, new PRED_current_prolog_flag_2(s1, a1, p3));
    }
}
