package jp.ac.kobe_u.cs.prolog.builtin;
import jp.ac.kobe_u.cs.prolog.lang.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>stream_property/2</code> defined in builtins.pl<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @author Douglas R. Miles (dmiles@users.sourceforge.net) for Object(s) 
 @version 1.0-dmiles
*/
public class PRED_stream_property_2 extends PredicateBase {
    static /*Symbol*/Object s1 = makeAtom("domain", 2);
    static /*Symbol*/Object s2 = makeAtom("term");
    static /*Symbol*/Object s3 = makeAtom("stream_proeprty");
    static Object[] s4 = {s2, s3};
    static /*Structure*/Object s5 = makeStructure(s1, s4);
    static /*Symbol*/Object s6 = makeAtom("stream_property", 2);
    static /*IntegerTerm*/Object si7 = makeInteger(2);
    static Predicate _stream_property_2_sub_1 = new PRED_stream_property_2_sub_1();
    static Predicate _stream_property_2_sub_2 = new PRED_stream_property_2_sub_2();
    static Predicate _stream_property_2_1 = new PRED_stream_property_2_1();
    static Predicate _stream_property_2_2 = new PRED_stream_property_2_2();
    static Predicate _stream_property_2_3 = new PRED_stream_property_2_3();

    public Object arg1, arg2;

    public PRED_stream_property_2(Object a1, Object a2, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        this.cont = cont;
    }

    public PRED_stream_property_2(){}

    public void setArgument(Object[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        this.cont = cont;
    }

    public int arity() { return 2; }

    public String nameUQ() { return "stream_property"; }

    public void sArg(int i0, Object val) {  switch (i0) {         case 0: arg1 = val;break ;
         case 1: arg2 = val;break ;
default: newIndexOutOfBoundsException("setarg" , i0 , val);  }   }


    public Object gArg(int i0) {  switch (i0) {         case 0: return arg1;
         case 1: return arg2;
default: return newIndexOutOfBoundsException("getarg", i0,null);  }   }


    public String toPrologString(java.util.Collection newParam) {
        return "'stream_property'(" + argString(arg1,newParam) + "," + argString(arg2,newParam) + ")";
    }

    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); 
        engine_aregs[1] = arg1;
        engine_aregs[2] = arg2;
        engine.cont = cont;
        engine.setB0();
        return engine.jtry(_stream_property_2_1, _stream_property_2_sub_1);
    }
}

class PRED_stream_property_2_sub_1 extends PRED_stream_property_2 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.retry(_stream_property_2_2, _stream_property_2_sub_2);
    }
}

class PRED_stream_property_2_sub_2 extends PRED_stream_property_2 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_stream_property_2_3);
    }
}

class PRED_stream_property_2_1 extends PRED_stream_property_2 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // stream_property(A, B):-var(B), !, '$stream_property'(A, B)
        Object a1, a2, a3;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        cont = engine.cont;
    // stream_property(A, B):-['$get_level'(C), var(B), '$cut'(C), '$stream_property'(A, B)]
        a3 = engine.makeVariable(this);
        //START inline expansion of $get_level(a(3))
        if (! unify(a3,makeInteger(engine.B0))) {
            return fail(engine);
        }
        //END inline expansion
        //START inline expansion of var(a(2))
        a2 = deref( a2);
        if (! isVariable(a2)) {
            return fail(engine);
        }
        //END inline expansion
        //START inline expansion of $cut(a(3))
        a3 = deref( a3);
        if (! isCutter/*Integer*/(a3)) {
            throw new IllegalTypeException("integer", a3);
        } else {
            engine.cut(( a3));
        }
        //END inline expansion
        return exit(engine, new PRED_$stream_property_2(a1, a2, cont));
    }
}

class PRED_stream_property_2_2 extends PRED_stream_property_2 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // stream_property(A, B):-'$stream_property_specifier'(B), !, '$stream_property'(A, B)
        Object a1, a2, a3;
        Predicate p1, p2;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        cont = engine.cont;
    // stream_property(A, B):-['$get_level'(C), '$stream_property_specifier'(B), '$cut'(C), '$stream_property'(A, B)]
        a3 = engine.makeVariable(this);
        //START inline expansion of $get_level(a(3))
        if (! unify(a3,makeInteger(engine.B0))) {
            return fail(engine);
        }
        //END inline expansion
        p1 = new PRED_$stream_property_2(a1, a2, cont);
        p2 = new PRED_$cut_1(a3, p1);
        return exit(engine, new PRED_$stream_property_specifier_1(a2, p2));
    }
}

class PRED_stream_property_2_3 extends PRED_stream_property_2 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // stream_property(A, B):-illarg(domain(term, stream_proeprty), stream_property(A, B), 2)
        Object a1, a2, a3;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        cont = engine.cont;
    // stream_property(A, B):-[illarg(domain(term, stream_proeprty), stream_property(A, B), 2)]
        Object[] y1 = {a1, a2};
        a3 = makeStructure(s6, y1);
        return exit(engine, new PRED_illarg_3(s5, a3, si7, cont));
    }
}
