package jp.ac.kobe_u.cs.prolog.builtin;
import jp.ac.kobe_u.cs.prolog.lang.*;
/*
 This file is generated by Prolog Cafe.
 PLEASE DO NOT EDIT!
*/
/**
 <code>'$dlength'/3</code> defined in builtins.pl<br>
 @author Mutsunori Banbara (banbara@kobe-u.ac.jp)
 @author Naoyuki Tamura (tamura@kobe-u.ac.jp)
 @author Douglas R. Miles (dmiles@users.sourceforge.net) for Object(s) 
 @version 1.0-dmiles
*/
class PRED_$dlength_3 extends PredicateBase {
    static /*Symbol*/Object s1 = makeAtom("[]");
    static /*IntegerTerm*/Object si2 = makeInteger(1);
    static Predicate _$dlength_3_top = new PRED_$dlength_3_top();
    static Predicate _fail_0 = new PRED_fail_0();
    static Predicate _$dlength_3_var = new PRED_$dlength_3_var();
    static Predicate _$dlength_3_var_1 = new PRED_$dlength_3_var_1();
    static Predicate _$dlength_3_1 = new PRED_$dlength_3_1();
    static Predicate _$dlength_3_2 = new PRED_$dlength_3_2();

    public Object arg1, arg2, arg3;

    public PRED_$dlength_3(Object a1, Object a2, Object a3, Predicate cont) {
        arg1 = a1;
        arg2 = a2;
        arg3 = a3;
        this.cont = cont;
    }

    public PRED_$dlength_3(){}

    public void setArgument(Object[] args, Predicate cont) {
        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        this.cont = cont;
    }

    public int arity() { return 3; }

    public String nameUQ() { return "$dlength"; }

    public void sArg(int i0, Object val) {  switch (i0) {         case 0: arg1 = val;break ;
         case 1: arg2 = val;break ;
         case 2: arg3 = val;break ;
default: newIndexOutOfBoundsException("setarg" , i0 , val);  }   }


    public Object gArg(int i0) {  switch (i0) {         case 0: return arg1;
         case 1: return arg2;
         case 2: return arg3;
default: return newIndexOutOfBoundsException("getarg", i0,null);  }   }


    public String toPrologString(java.util.Collection newParam) {
        return "'$dlength'(" + argString(arg1,newParam) + "," + argString(arg2,newParam) + "," + argString(arg3,newParam) + ")";
    }

    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); 
        engine_aregs[1] = arg1;
        engine_aregs[2] = arg2;
        engine_aregs[3] = arg3;
        engine.cont = cont;
        return exit(engine, _$dlength_3_top);
    }
}

class PRED_$dlength_3_top extends PRED_$dlength_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        engine.setB0();
        return engine.switch_on_term(_$dlength_3_var, _fail_0, _fail_0, _$dlength_3_1, _fail_0, _$dlength_3_2);
    }
}

class PRED_$dlength_3_var extends PRED_$dlength_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.jtry(_$dlength_3_1, _$dlength_3_var_1);
    }
}

class PRED_$dlength_3_var_1 extends PRED_$dlength_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
        return engine.trust(_$dlength_3_2);
    }
}

class PRED_$dlength_3_1 extends PRED_$dlength_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$dlength'([], A, A):-!
        Object a1, a2, a3;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        cont = engine.cont;
    // '$dlength'([], A, A):-['$neck_cut']
        a1 = deref( a1);
        if (isAtomTerm(a1)){
            if (! prologEquals(a1,s1))
                return fail(engine);
        } else if (isVariable(a1)){
             bind(/*VAR*/ a1,s1);
        } else {
            return fail(engine);
        }
        if (! unify(a2,a3))
            return fail(engine);
        //START inline expansion of $neck_cut
        engine.neckCut();
        //END inline expansion
        return exit(engine,cont);
    }
}

class PRED_$dlength_3_2 extends PRED_$dlength_3 {
    public Predicate exec(Prolog engine) { enter(engine); Object[] engine_aregs = engine.getAreg(); //anony 
    // '$dlength'([A|B], C, D):-C<D, E is C+1, '$dlength'(B, E, D)
        Object a1, a2, a3, a4, a5;
        Predicate cont;
        a1 = engine_aregs[1];
        a2 = engine_aregs[2];
        a3 = engine_aregs[3];
        cont = engine.cont;
    // '$dlength'([A|B], C, D):-['$less_than'(C, D), '$plus'(C, 1, E), '$dlength'(B, E, D)]
        a1 = deref( a1);
        if (isListTerm(a1)){
            Object[] args = consArgs(a1);
            a4 = args[1];
        } else if (isVariable(a1)){
            a4 = engine.makeVariable(this);
             bind(a1,makeList(engine.makeVariable(this), a4));
        } else {
            return fail(engine);
        }
        //START inline expansion of $less_than(a(2), a(3))
        try {
            if (arithCompareTo(Arithmetic.evaluate(a2),Arithmetic.evaluate(a3)) >= 0) {
                return fail(engine);
            }
        } catch (BuiltinException e) {
            e.goal = this;
            throw e;
        }
        //END inline expansion
        a5 = engine.makeVariable(this);
        //START inline expansion of $plus(a(2), si(2), a(5))
        try {
            if (! unify(a5,add(Arithmetic.evaluate(a2),si2))) {
                return fail(engine);
            }
        } catch (BuiltinException e) {
            e.goal = this;
            throw e;
        }
        //END inline expansion
        engine_aregs[1] = a4;
        engine_aregs[2] = a5;
        engine_aregs[3] = a3;
        engine.cont = cont;
        return exit(engine, _$dlength_3_top);
    }
}
