// Copyright © 2000 Microsoft Corporation.  All rights reserved.
// In installing/viewing this source code, you agree to the terms of the
// Microsoft Research Source License (MSRSL) included in the root of this source tree
// and available from http://www.vworlds.org/license.asp.

// VWGeom.idl : IDL source for VWGeom.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (VWGeom.tlb) and marshalling code.

	import "VWGeom.idl";

#ifdef VWGEOMLIB
[
	uuid(CFC0B260-1DDB-11D0-89A9-00A0C9054129),
	version(1.0),
	helpstring("VWGeom 1.0 Type Library")
]
library VWGEOMLib
{
	importlib("stdole32.tlb");

	[
		uuid(CFC0B266-1DDB-11D0-89A9-00A0C9054129),
		helpstring("VWGeometry Class")
	]
	coclass VWGeometry
	{
		[default] interface IVWGeometry;
	};

};
#endif