#!/bin/csh -f

pushd OKBC/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd demos/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd Jot/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd OKBCUI/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd OOBN/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd SQLKB/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
java polardoc.Main -d doc -r -verbose OKBC demos Jot OKBCUI OOBN
