#!/bin/csh -f

pushd /q/htw/cms/nokbc/java/OKBC/
make clean
popd
pushd OKBC/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd /q/htw/cms/nokbc/java/demos/
make clean
popd
pushd demos/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd /q/htw/cms/nokbc/java/Jot/
make clean
popd
pushd Jot/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd /q/htw/cms/nokbc/java/OKBCUI/
make clean
popd
pushd OKBCUI/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd /q/htw/cms/nokbc/java/OOBN/
make clean
popd
pushd OOBN/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
pushd /q/htw/cms/nokbc/java/SQLKB/
make clean
popd
pushd SQLKB/
make
chgrp -R cms *; chmod -R a+rX,ug+w *
popd
javadoc -J-ms64m -J-mx64m -d doc OKBC demos Jot OKBCUI OOBN
