// Copyright © 2000 Microsoft Corporation.  All rights reserved.
// In installing/viewing this source code, you agree to the terms of the
// Microsoft Research Source License (MSRSL) included in the root of this source tree
// and available from http://www.vworlds.org/license.asp.

// vwmm.idl : IDL source for vwmm.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (vwmm.tlb) and marshalling code.

	import "oaidl.idl";
	import "ocidl.idl";

	// stdtools
	import "stdtools.idl";

	// geomtool
	import "geomtool.idl";

	// boundarytools
	import "bndytool.idl";

	// popupmgr
//	import "popup.idl";
//	import "popupmgr.idl";
			
	// webtools
	import "webtools.idl";

	// popup editors

	// modules
	import "vwstuex.idl";


[
	uuid(88FBF974-6D18-11d1-959E-00C04FD91F4D),
	version(1.0),
	helpstring("vwstudio 1.0 Type Library")
]
library VWSTUDIOLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

// from stdtools.idl

	[
		uuid(77B43660-792E-11d0-89AB-00A0C9054129),
		helpstring("VWErrorTool Class")
	]
	coclass VWErrorTool
	{
		[default] interface IVWErrorTool;
	};

	[
		uuid(3159FDB2-EF7F-11CF-89A9-00A0C9054129),
		helpstring("VWTranslate2DTool Class")
	]
	coclass VWTranslate2DTool
	{
		[default] interface IVWTranslate2DTool;
	};

	[
		uuid(3159FDB7-EF7F-11CF-89A9-00A0C9054129),
		helpstring("VWSelectTool Class")
	]
	coclass VWSelectTool
	{
		[default] interface IVWSelectTool;
	};

	[
		uuid(FF41E720-30B4-11d0-89A9-00A0C9054129),
		helpstring("UndoStack Class")
	]
	coclass VWUndoStacks
	{
		[default] interface IVWUndoStacks;
	};

	[
		uuid(FFF1E320-30B4-31d0-83A9-03A019044129),
		helpstring("ControlManager Class")
	]
	coclass VWControlManager
	{
		[default] interface IVWControlManager;
	};

	[
		uuid(B0CD7B7A-AD1E-11D0-888B-00C04FC32EF3),
		helpstring("UndoItem Class")
	]
	coclass VWUndoItem
	{
		[default] interface IVWUndoItem;
	};

	[
		uuid(FFF1E320-30B4-31d0-13A9-13A019044129),
		helpstring("ControlManager Class")
	]
	coclass VWRotate2DTool
	{
		[default] interface IVWRotate2DTool;
	};

	[
		uuid(056BA0D2-C31A-11D0-AFB6-00C04FB68E58),
		helpstring("PolyTool Class")
	]
	coclass PolyTool
	{
		[default] interface IPolyTool;
	};

	[
		uuid(76BD302B-515C-11d1-B33A-00C04FB6A5C8),
		helpstring("Scale2D Class")
	]
	coclass VWScale2DTool
	{
		[default] interface IVWScale2DTool;
	};

// from geomtool
	[
		uuid(86CD4C80-9A10-11D0-89AB-00A0C9054129),
		helpstring("VWTranslate3DTool Class")
	]
	coclass VWTranslate3DTool
	{
		[default] interface IVWTranslate3DTool;
	};

	[
		uuid(0A1D4363-A12B-11D0-89AB-00A0C9054129),
		helpstring("Rotate3DTool Class")
	]
	coclass Rotate3DTool
	{
		[default] interface IRotate3DTool;
	};

	[
		uuid(9B813D83-A148-11D0-89AB-00A0C9054129),
		helpstring("VWScale3DTool Class")
	]
	coclass VWScale3DTool
	{
		[default] interface IVWScale3DTool;
	};

	[
		uuid(C461BF77-DDDA-11D0-8899-00C04FC32EF3),
		helpstring("VWExecuteGeomUndo Class")
	]
	coclass VWExecuteGeomUndo
	{
		[default] interface IVWExecuteUndo;
	};

// from webtools
	[
		uuid(969AD685-5B00-11D1-88AE-00C04FC32EF3),
		helpstring("WorldWizHelper Class")
	]
	coclass WorldWizHelper
	{
		[default] interface IWorldWizHelper;
	};

	[
		uuid(969AD685-5B00-11D1-88AE-00C04FC32EF4),
		helpstring("RoomWizHelper Class")
	]
	coclass RoomWizHelper
	{
		[default] interface IRoomWizHelper;
	};

// from vwstuex.idl
	[
		uuid(717B5AA4-7267-11d1-959F-00C04FD91F4D),
		helpstring("StudioExemplar Class")
	]
	coclass StudioExemplar
	{
		[default] interface IStudioExemplar;
	};

	[
		uuid(F5B9E8D3-74C4-11D1-B344-00C04FB6A5C8),
		helpstring("VWFileAccessTool Class")
	]
	coclass VWFileAccessTool
	{
		[default] interface IVWFileAccessTool;
	};
	[
		uuid(E0B64D5E-764A-11D1-B345-00C04FB6A5C8),
		helpstring("VWZoomTool Class")
	]
	coclass VWZoomTool
	{
		[default] interface IVWZoomTool;
	};
};
